// <auto-generated />
using System;
using System.Collections.Generic;
using Arthur_Showdown_Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arthur_Showdown_Database.Migrations
{
    [DbContext(typeof(ArthurShowdownContext))]
    [Migration("20260906200758_AdicionandoMetagame")]
    partial class AdicionandoMetagame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.Efeito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Efeitos");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocalId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroSessao")
                        .HasColumnType("integer");

                    b.Property<int>("TamanhoMapa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.StatusRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusRuns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Em Andamento"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Vitoria"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Derrota"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Desistencia"
                        });
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.TipoPersonagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposPersonagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Playable"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Enemy"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Npc"
                        });
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.Wave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QtdInimigos")
                        .HasColumnType("integer");

                    b.Property<int>("SessaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId");

                    b.ToTable("Waves");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Ataque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cooldown")
                        .HasColumnType("integer");

                    b.Property<int>("Dano")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EfeitoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFastAction")
                        .HasColumnType("boolean");

                    b.Property<int>("LimiteAprimoramento")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EfeitoId");

                    b.ToTable("Ataques");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustoCompra")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustoCompra")
                        .HasColumnType("integer");

                    b.Property<int>("CustoVenda")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChefeId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("InimigosPossiveisIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdemProgressao")
                        .HasColumnType("integer");

                    b.Property<int>("QtdSessoes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChefeId");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoPersonagemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoPersonagemId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.ProgressoJogador", b =>
                {
                    b.Property<Guid>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<int>>("AtaquesDesbloqueadosIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("EmblemasKamelot")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("HabilidadesDesbloqueadasIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<int>>("PersonagensDesbloqueadosIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("JogadorId");

                    b.ToTable("ProgressoJogadores");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.DeckAtaques", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtaqueId")
                        .HasColumnType("integer");

                    b.Property<int?>("EfeitoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFastAction")
                        .HasColumnType("boolean");

                    b.Property<int>("LimiteUpgrade")
                        .HasColumnType("integer");

                    b.Property<int>("ModCooldown")
                        .HasColumnType("integer");

                    b.Property<int>("ModDano")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroDeUpgrades")
                        .HasColumnType("integer");

                    b.Property<int>("PersonagemRunId")
                        .HasColumnType("integer");

                    b.Property<int>("QtdUsosNaRun")
                        .HasColumnType("integer");

                    b.Property<int>("QtdVezesAdicionadoFila")
                        .HasColumnType("integer");

                    b.Property<int>("QtdVezesRemovidoFila")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtaqueId");

                    b.HasIndex("EfeitoId");

                    b.HasIndex("PersonagemRunId");

                    b.ToTable("DecksAtaques");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid");

                    b.Property<int>("LocalAtualId")
                        .HasColumnType("integer");

                    b.Property<int>("OuroAtual")
                        .HasColumnType("integer");

                    b.Property<int>("QtdHitsSofridos")
                        .HasColumnType("integer");

                    b.Property<int>("QtdMudancaDirecao")
                        .HasColumnType("integer");

                    b.Property<int?>("SessaoAtualId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusRunId")
                        .HasColumnType("integer");

                    b.Property<int>("TempoSegundos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOuroGanho")
                        .HasColumnType("integer");

                    b.Property<int>("TurnosJogados")
                        .HasColumnType("integer");

                    b.Property<int?>("WaveAtualId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalAtualId");

                    b.HasIndex("SessaoAtualId");

                    b.HasIndex("StatusRunId");

                    b.HasIndex("WaveAtualId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.HabilidadesRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonagemRunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadeId");

                    b.HasIndex("PersonagemRunId");

                    b.ToTable("HabilidadesRun");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonagemRunId")
                        .HasColumnType("integer");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PersonagemRunId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.PersonagemRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("integer");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("integer");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagensRun");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.WaveAtual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("InimigosGeradosIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("WavesAtuais");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.Sessao", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Base.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.Wave", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Auxiliar.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Ataque", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Auxiliar.Efeito", "Efeito")
                        .WithMany()
                        .HasForeignKey("EfeitoId");

                    b.OwnsOne("Arthur_Showdown_Database.Models.Base.HitboxConfig", "Hitbox", b1 =>
                        {
                            b1.Property<int>("AtaqueId");

                            b1.Property<int>("AlcanceMax");

                            b1.Property<int>("AlcanceMin");

                            b1.Property<int>("Direcao");

                            b1.Property<int>("Origem");

                            b1.HasKey("AtaqueId");

                            b1.ToTable("Ataques");

                            b1
                                .ToJson("Hitbox")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AtaqueId");
                        });

                    b.Navigation("Efeito");

                    b.Navigation("Hitbox")
                        .IsRequired();
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Local", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Base.Personagem", "Chefe")
                        .WithMany()
                        .HasForeignKey("ChefeId");

                    b.Navigation("Chefe");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Base.Personagem", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Auxiliar.TipoPersonagem", "TipoPersonagem")
                        .WithMany("Personagens")
                        .HasForeignKey("TipoPersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPersonagem");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.DeckAtaques", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Base.Ataque", "Ataque")
                        .WithMany()
                        .HasForeignKey("AtaqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arthur_Showdown_Database.Models.Auxiliar.Efeito", "Efeito")
                        .WithMany()
                        .HasForeignKey("EfeitoId");

                    b.HasOne("Arthur_Showdown_Database.Models.Run.PersonagemRun", "PersonagemRun")
                        .WithMany()
                        .HasForeignKey("PersonagemRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ataque");

                    b.Navigation("Efeito");

                    b.Navigation("PersonagemRun");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.Game", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Base.Local", "LocalAtual")
                        .WithMany()
                        .HasForeignKey("LocalAtualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arthur_Showdown_Database.Models.Auxiliar.Sessao", "SessaoAtual")
                        .WithMany()
                        .HasForeignKey("SessaoAtualId");

                    b.HasOne("Arthur_Showdown_Database.Models.Auxiliar.StatusRun", "StatusRun")
                        .WithMany()
                        .HasForeignKey("StatusRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arthur_Showdown_Database.Models.Run.WaveAtual", "WaveAtual")
                        .WithMany()
                        .HasForeignKey("WaveAtualId");

                    b.Navigation("LocalAtual");

                    b.Navigation("SessaoAtual");

                    b.Navigation("StatusRun");

                    b.Navigation("WaveAtual");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.HabilidadesRun", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Base.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arthur_Showdown_Database.Models.Run.PersonagemRun", "PersonagemRun")
                        .WithMany()
                        .HasForeignKey("PersonagemRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("PersonagemRun");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.Inventario", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Base.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arthur_Showdown_Database.Models.Run.PersonagemRun", "PersonagemRun")
                        .WithMany()
                        .HasForeignKey("PersonagemRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PersonagemRun");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.PersonagemRun", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Run.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arthur_Showdown_Database.Models.Base.Personagem", "Personagem")
                        .WithMany()
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Run.WaveAtual", b =>
                {
                    b.HasOne("Arthur_Showdown_Database.Models.Run.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Arthur_Showdown_Database.Models.Auxiliar.TipoPersonagem", b =>
                {
                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
